{"retry":0,"creationTime":1523448642839,"lastModificationTime":1523448888563,"state":"TERMINATED","solveConfig":{"containerId":"Scenario 1","collectEngineLog":true,"solveParameters":{"oaas.logAttachmentName":"log.txt","oaas.logTailEnabled":"true"}},"jobId":"job.70ba1931-4794-43f4-a32b-1c5eed65dc01","transactionId":"7fe82d22-54e9-40a8-973e-f579ac7f30b3","dataContainerId":"801b92cc-2021-4a91-b86f-5ea1447c71f2","jobDetails":{"id":"job.70ba1931-4794-43f4-a32b-1c5eed65dc01","createdAt":1523448645444,"startedAt":1523448645539,"endedAt":1523448890742,"endReportedAt":1523448890784,"submittedAt":1523448645444,"updatedAt":1523448890742,"applicationVersionUsed":"1.0-R1-b4181","details":{"MODEL_DETAIL_KPIS":"[\"time to complete all Tasks\", \"total Unperformed Penalty Cost of unperformed Tasks\", \"transit cost between assigned Tasks based on Transition_Matrices\"]"},"systemDetails":{"worker.process.max.memory":"524288","worker.cores.total":"8","worker.cores.default":"1","worker.process.cpu.set":null,"worker.heap.max":"524288","worker.data.read.bytes":"230856","worker.data.write.duration":"192","worker.processing.duration":"245150","worker.process.peak.swap":"0","worker.log.write.duration":"8","worker.process.processing.duration":"244286","worker.data.read.duration":"147","worker.jms.write.chars":"289596","worker.log.write.chars":"1851","worker.data.write.bytes":"2529","worker.heap.used":"140482","worker.process.peak.memory":"387984","worker.setup.duration":"34","worker.jms.write.duration":"217"},"executionStatus":"FAILED","failureInfo":{"type":"PROCESSING","message":"InterpreterError :   File \"model.py\", line 725, in <module>\n    solve_model(model)\n  File \"<string>\", line 651, in solve_model\nLocalSolverException: Nothing to read from local solver process. Process seems to have been stopped.\n"},"solveStatus":"UNKNOWN","logTail":["[2018-04-11T12:10:45Z, INFO] * building wado model","[2018-04-11T12:14:41Z, INFO] model building done in 235.581580877 secs","[2018-04-11T12:14:41Z, INFO] * running wado model","[2018-04-11T12:14:41Z, INFO] WARNING: Number of workers has been reduced to 1 to comply with platform limitations.","[2018-04-11T12:14:45Z, INFO] stream:7:4: Warning: Reading file created by CP Optimizer version 12.7.0.0 into CP Optimizer version 12.8.0.0.","[2018-04-11T12:14:45Z, INFO] stream:7:4: Warning: Making reader backward compatible with version 12.7.0.0.","[2018-04-11T12:14:48Z, INFO]  ! ----------------------------------------------------------------------------","[2018-04-11T12:14:48Z, INFO]  ! Minimization problem - 14887 variables, 44961 constraints","[2018-04-11T12:14:48Z, INFO]  ! Presolve      : 31496 extractables eliminated, 5200 constraints generated","[2018-04-11T12:14:48Z, INFO]  ! TimeLimit            = 60","[2018-04-11T12:14:48Z, INFO]  ! Workers              = 1","[2018-04-11T12:14:48Z, INFO]  ! Initial process time : 1.71s (1.70s extraction + 0.00s propagation)","[2018-04-11T12:14:48Z, INFO]  !  . Log search space  : 13008.0 (before), 13008.0 (after)","[2018-04-11T12:14:48Z, INFO]  !  . Memory usage      : 46.8 MB (before), 46.8 MB (after)","[2018-04-11T12:14:48Z, INFO]  ! Using sequential search.","[2018-04-11T12:14:48Z, INFO]  ! ----------------------------------------------------------------------------","[2018-04-11T12:14:48Z, INFO]  !          Best Branches  Non-fixed            Branch decision","[2018-04-11T12:14:48Z, INFO]                         0      14887                 -","[2018-04-11T12:14:48Z, INFO]  + New bound is 0","[2018-04-11T12:14:48Z, INFO]  ! Using temporal relaxation.","[2018-04-11T12:14:48Z, INFO]                         0       4680                 -","[2018-04-11T12:14:48Z, INFO]  + New bound is 670823","[2018-04-11T12:14:49Z, INFO]                      2469       4680            on _ITV_14760","[2018-04-11T12:14:49Z, INFO]  *     104000000     2469  2.23s               (gap is 99.35%)","[2018-04-11T12:14:50Z, SEVERE] InterpreterError :   File \"model.py\", line 725, in <module>\n    solve_model(model)\n  File \"<string>\", line 651, in solve_model\nLocalSolverException: Nothing to read from local solver process. Process seems to have been stopped.\n\nTraceback (most recent call last):\n  File \"/python_container/job/main.py\", line 120, in <module>\n    raise InterpreterError(imsg)\n","[2018-04-11T12:14:50Z, INFO] An exception has been raised: Nothing to read from local solver process. Process seems to have been stopped."]},"runtimeDetails":{"state":"STARTED"},"taskSetupMillis":289,"taskSolveMillis":245304,"taskTearDownMillis":1,"jobUri":"http://dods-processor-server-1523446866723-1168-svc/dd-execution/api/v1/solve/job.70ba1931-4794-43f4-a32b-1c5eed65dc01"}